name = "Twenty Fourteen"
license = "MIT"
description = "Copy of Wordpress theme of the same name"
tags = ["blog", "wordpress"]
features = ["blog", ]

[author]
    name = "Dan Hersam"
    homepage = "http://dan.hersam.com"

[original]
    author =  "wordpressdotorg"
    homepage = "https://wordpress.org/themes/twentyfourteen"
    repo = "https://themes.trac.wordpress.org/browser/twentyfourteen/1.2"
